version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - redis
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - redis
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    environment:
      REDIS_HOST: ${REDIS_HOST}


  redis:
    image: redislabs/rejson:latest
    container_name: redis.redisshoppingcart
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: demo
    command: redis-server --loadmodule "/usr/lib/redis/modules/rejson.so" --requirepass "demo"
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  db_data:
