version: '3.8'

services:

  redis:
    image: redislabs/rejson:latest
    container_name: redis.redisshoppingcart
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: demo
    command: redis-server --loadmodule "/usr/lib/redis/modules/rejson.so" --requirepass "demo"
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  db_data:
